<template>
  <div class="experiments-section">
    <h2 class="section-title">Experiments</h2>

    <div class="experiments-content">
      <div class="quantitative-section">
        <h3 class="subsection-title">Quantitative Comparisons</h3>

        <div class="experiment-tables">
          <div class="table-item">
            <img
              src="/table1-lol.png"
              alt="Quantitative comparisons on LOL-v2 for low-light enhancement"
              class="table-image"
            />
            <p class="table-caption">
              Table 1. Quantitative comparisons on LOL-v2 for low-light enhancement
            </p>
          </div>

          <div class="table-item">
            <img
              src="/table2-snow.png"
              alt="Quantitative results on Snow100K for snow removal"
              class="table-image"
            />
            <p class="table-caption">Table 2. Quantitative results on Snow100K for snow removal</p>
          </div>

          <div class="table-item">
            <img
              src="/table3-haze.png"
              alt="Quantitative comparison on SOTS for haze removal"
              class="table-image"
            />
            <p class="table-caption">Table 3. Quantitative comparison on SOTS for haze removal</p>
          </div>
        </div>
      </div>

      <div class="visual-section">
        <h3 class="subsection-title">Visual Comparisons</h3>

        <div class="visual-gallery">
          <!-- 第一行：两个大图并排 -->
          <div class="visual-row main-comparisons">
            <div class="visual-item large">
              <img
                src="/visual-1.png"
                alt="Results on LOL-v2 for low-light enhancement"
                class="visual-img"
              />
              <p class="visual-caption">
                <strong>Low-light Enhancement (LOL-v2):</strong> Results on LOL-v2 [77] for
                low-light enhancement. The top case is from the synthetic subset, whereas the bottom
                one is from the real subset. Compared to other techniques, HINT generates vivid
                images without introducing noticeable color distortion.
              </p>
            </div>
            <div class="visual-item large">
              <img
                src="/visual-2.png"
                alt="Results on Snow100K for snow removal"
                class="visual-img"
              />
              <p class="visual-caption">
                <strong>Snow Removal (Snow100K):</strong> Results on Snow100K [42] for snow removal.
                HINT offers a clear result, while the images generated by other considered
                approaches remain noticeable snow artifacts.
              </p>
            </div>
          </div>

          <!-- 第二行：三个中等大小的图 -->
          <div class="visual-row secondary-comparisons">
            <div class="visual-item medium">
              <img src="/visual-3.png" alt="Results on SOTS for haze removal" class="visual-img" />
              <p class="visual-caption">
                <strong>Haze Removal (SOTS):</strong> Results on SOTS [33] benchmark for haze
                removal. The image generated by HINT is closer to the reference one, compared to
                other methods.
              </p>
            </div>
            <div class="visual-item medium">
              <img src="/visual-4.png" alt="Feature visualization comparison" class="visual-img" />
              <p class="visual-caption">
                <strong>Feature Visualization:</strong> The top line shows feature maps of each head
                learned by MDTA, while the bottom illustrates HMHA results. MDTA heads focus on same
                regions (red boxes), whereas HMHA heads learn from different subspaces, producing
                better restoration (yellow boxes).
              </p>
            </div>
            <div class="visual-item medium">
              <img
                src="/visual-5.png"
                alt="Real-world benchmark visualizations"
                class="visual-img"
              />
              <p class="visual-caption">
                <strong>Real-world Benchmarks:</strong> Visualizations on NPE [65], DICM [31], VV
                [61], and MEF [46] (top to bottom). HINT restores pleasant results, whereas other
                methods suffer from under-/over-exposure, color distortion, or significant
                artifacts.
              </p>
            </div>
          </div>

          <!-- 第三行：两个图并排 -->
          <div class="visual-row bottom-comparisons">
            <div class="visual-item medium">
              <img
                src="/visual-6.png"
                alt="Low-light object detection comparison"
                class="visual-img"
              />
              <p class="visual-caption">
                <strong>Object Detection:</strong> Visual comparison of low-light object detection.
                Compared to the low-light input (left), the detector can predict a well-placed
                bounding box on the image restored by HINT (right).
              </p>
            </div>
            <div class="visual-item medium">
              <img src="/visual-7.png" alt="Failure case example" class="visual-img" />
              <p class="visual-caption">
                <strong>Failure Case:</strong> HINT, which is pre-trained on the synthetic dataset,
                meets challenges of restoring input under extremely low-light conditions.
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="results-analysis">
        <p>
          The experimental results demonstrate the effectiveness of our HINT method across multiple
          challenging image restoration tasks. The quantitative comparisons show that HINT achieves
          state-of-the-art performance on low-light enhancement (LOL-v2 dataset), snow removal
          (Snow100K dataset), and haze removal (SOTS dataset), consistently outperforming existing
          methods in terms of PSNR and SSIM metrics through its innovative hierarchical attention
          mechanism and diverse learner integration.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
.experiments-section {
  text-align: center;
}

.section-title {
  font-size: 32px;
  font-weight: bold;
  color: #2c3e50;
  margin-bottom: 30px;
  text-align: center;
  font-family: 'Times New Roman', serif;
}

.experiments-content {
  margin-top: 20px;
}

.subsection-title {
  font-size: 22px;
  font-weight: 600;
  color: #2d3748;
  margin-bottom: 20px;
  text-align: center;
  font-family: 'Times New Roman', serif;
}

.experiment-tables {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 25px;
  margin-bottom: 40px;
  padding: 0 20px;
}

.table-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  background: white;
  border-radius: 8px;
  padding: 15px;
  border: 1px solid #dee2e6;
}

.table-image {
  width: 100%;
  height: auto;
  border-radius: 6px;
  margin-bottom: 10px;
}

.table-caption {
  font-size: 13px;
  color: #666;
  font-style: italic;
  margin: 0;
  text-align: center;
  line-height: 1.3;
}

.tables-image {
  max-width: 100%;
  height: auto;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}

.visual-section {
  margin-bottom: 40px;
}

.visual-gallery {
  display: flex;
  flex-direction: column;
  gap: 30px;
  padding: 0 20px;
}

.visual-row {
  display: flex;
  gap: 20px;
  justify-content: center;
  flex-wrap: wrap;
}

.main-comparisons {
  gap: 25px;
}

.secondary-comparisons {
  gap: 18px;
}

.bottom-comparisons {
  gap: 22px;
}

.visual-item {
  background: white;
  border-radius: 10px;
  border: 1px solid #dee2e6;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.visual-item.large {
  flex: 1;
  max-width: 480px;
  min-width: 300px;
}

.visual-item.medium {
  flex: 1;
  max-width: 320px;
  min-width: 280px;
}

.visual-img {
  width: 100%;
  height: auto;
  display: block;
  object-fit: cover;
}

.visual-item.large .visual-img {
  max-height: 320px;
}

.visual-item.medium .visual-img {
  max-height: 240px;
}

.visual-caption {
  padding: 18px 20px;
  font-size: 13px;
  color: #555;
  margin: 0;
  text-align: justify;
  line-height: 1.5;
  background: linear-gradient(to bottom, #f8f9fa, #f1f3f4);
  border-top: 1px solid #e9ecef;
  min-height: auto;
}

.visual-caption strong {
  color: #2c3e50;
  font-weight: 600;
  display: block;
  margin-bottom: 6px;
  font-style: normal;
}

.visual-item.large .visual-caption {
  padding: 20px 22px;
  font-size: 14px;
  line-height: 1.6;
}

.visual-item.medium .visual-caption {
  padding: 16px 18px;
  font-size: 12px;
  line-height: 1.5;
}

.visual-comparisons {
  display: flex;
  flex-direction: column;
  gap: 24px;
  align-items: center;
}

.comparison-image {
  width: 100%;
  text-align: center;
}

.comparison-img {
  width: 100%;
  max-width: 800px;
  height: auto;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  object-fit: contain;
}

.image-caption {
  font-size: 14px;
  color: #666;
  font-style: italic;
  margin-top: 10px;
  line-height: 1.4;
  text-align: center;
}

.results-analysis {
  background: #f8f9fa;
  padding: 35px;
  border-radius: 10px;
  border: 1px solid #e9ecef;
  font-size: 18px;
  text-align: justify;
  line-height: 1.8;
  color: #444;
  font-family: 'Times New Roman', serif;
  margin-top: 24px;
}

.results-analysis p {
  margin: 0;
}

.results-analysis strong {
  color: #e74c3c;
  font-weight: bold;
}

@media (max-width: 768px) {
  .experiment-tables {
    grid-template-columns: 1fr;
    gap: 20px;
    padding: 0 10px;
  }

  .table-item {
    padding: 12px;
  }

  .table-caption {
    font-size: 12px;
  }

  .visual-gallery {
    padding: 0 10px;
    gap: 25px;
  }

  .visual-row {
    flex-direction: column;
    align-items: center;
    gap: 20px;
  }

  .visual-item.large,
  .visual-item.medium {
    max-width: 100%;
    min-width: unset;
    width: 100%;
  }

  .visual-item.large .visual-img {
    max-height: 280px;
  }

  .visual-item.medium .visual-img {
    max-height: 220px;
  }

  .visual-caption {
    padding: 15px 16px;
    font-size: 12px;
    line-height: 1.4;
  }

  .visual-caption strong {
    margin-bottom: 5px;
    font-size: 13px;
  }

  .results-analysis {
    padding: 20px;
    font-size: 16px;
  }

  .section-title {
    font-size: 28px;
  }

  .subsection-title {
    font-size: 20px;
  }
}

@media (max-width: 1024px) and (min-width: 769px) {
  .main-comparisons {
    gap: 20px;
  }

  .secondary-comparisons {
    gap: 15px;
  }

  .visual-item.large {
    max-width: 420px;
  }

  .visual-item.medium {
    max-width: 280px;
  }
}
</style>
